spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_pacientes
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true

    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8088/realms/your-realm/protocol/openid-connect/certs

    cloud:
      config:
        enabled: false

  server:
    port: 8086
    # -------------------------------
    # EUREKA CLIENT
    # -------------------------------
    eureka:
      client:
        service-url:
          defaultZone: http://eureka-server:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
      instance:
        prefer-ip-address: true

